en:
  menu:
    main:
      - name: "Blog"
        weight: "1"
        url: "posts/"
      - name: "Work"
        weight: "2"
        url: "projects/"
      - name: "Experiments"
        weight: "3"
        url: "experiments/"
      - name: "Meta"
        weight: "4"
        url: "meta/"
      - name: "Self"
        weight: "5"
        url: "about/"
